module.exports = {
    "bg":{
        backgroundColor:"#1A1C1E",
    },
    "bg-orange":{
        backgroundColor:"#F96E4F",
    },
    "bg-yellow":{
        backgroundColor:"#EAC652",
    },
    "bg-blue":{
        backgroundColor:"#2D9BF0",
    },
    "bg-dark-blue":{
        backgroundColor:"#414BB2",
    },
    "bg-white":{
        backgroundColor:"#FFFFFF",
    },
    "bg-black":{
        backgroundColor:"#000000",
    },
    "orange":{
        color:"#F96E4F",
    },
    "yellow":{
        color:"#EAC652",
    },
    "blue":{
        color:"#2D9BF0",
    },
    "black":{
        color:"#000000",
    },
    "white":{
        color:"#FFFFFF",
    }
}